### ISSUE TITLE
Agricraft localization needed

### ISSUE THREAD

**Issue by claybiockiller** [S--Minecraft/MinecraftModLangFiles#5]
Dear S--minecraft,
Hello!
I'm Clayblockiller, a minecraft mod localizer from China. I think Agricraft (https://github.com/InfinityRaider/AgriCraft) need Japanese localization. But my Japanese is poor so I need help from native Japanese speaker. Can you give me a favor?
Clayblockiller

**Comment by S--Minecraft** [comment]
@claybiockiller 
Hello!
All right.
So what should I do? Tell you some advice with localization by you or something?
S--Minecraft

**Comment by claybiockiller** [comment]
Dear S--minecraft,
Hello!
I think you can made a japanese language file for Agricraft.
Clayblockiller

**Comment by S--Minecraft** [comment]
@claybiockiller 
Im afraid that I cant make a Japanese language file for Agricraft because I cant make much time for that.
Could you find another person to ask?
S--Minecraft
