### ISSUE TITLE
Request to use the FrogCraft localization

### ISSUE THREAD

**Issue by 3TUSK** [S--Minecraft/MinecraftModLangFiles#7]
Hi there. Currently I am developing a mod called [FrogCraft: Rebirth](https://github.com/FrogCraft-Rebirth/FrogCraft-Rebirth) and it is basically an unofficial continuation of original FrogCraft. Right now although there are several unimplemented things, the mod becomes stable now, and then I start to look for translation. 
I notice that there is a [Japanese translation for FrogCraft](https://github.com/S--Minecraft/MinecraftModLangFiles/blob/master/FrogCraft/1.2/en_US.properties) here. May I adapt it and include it in my incoming new mod? Thanks for your time.

**Comment by S--Minecraft** [comment]
Hi.
Yes you can.
But just remind that I may not update the translation for new versions.
Shoud I fork the source and PR?
Thanks.

**Comment by 3TUSK** [comment]
There is no big change though... and yes pull request are welcome :)
